
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig, env } from "prisma/config";

// Для npm run db:push используем локальный SQLite (как в приложении через db.ts)
const useSqlite = process.env.USE_SQLITE === "1";
const sqlitePath = path.join(process.cwd(), "prisma", "dev.db");
const datasourceUrl = useSqlite ? `file:${sqlitePath}` : env("DATABASE_URL");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: datasourceUrl,
  },
});
